name: Linter
on: [pull_request]

jobs:
  ruby-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@v2.0.0
      with:
        additional_gems: 'rubocop-performance'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
